### ISSUE TITLE
no sanitisation for command name

### ISSUE THREAD

**Issue by n1ckl0sk0rtge** [n1ckl0sk0rtge/cpm#14]
In case a new command is created, there is no sanitisation for the new command name. If such a name contains a '.' the program will parse it as a new level for the yaml-config.

Input
```shell
cpm create golang@1.17 golang:1.17-stretch -c go
```

Config
```yaml
container:
  golang@1:
    "17":
      command: go
      image: golang
      parameter: -i -t --rm
      path: /usr/local/bin/golang@1.17
      tag: 1.17-stretch
```
